ALTER TABLE outbox
ADD COLUMN retry_count INT NOT NULL DEFAULT 0,
ADD COLUMN next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
ADD COLUMN locked_at TIMESTAMPTZ NULL,
ADD COLUMN locker_by VARCHAR(100) NULL,
ADD COLUMN last_error TEXT NULL;