ALTER TABLE order_items
ALTER COLUMN created_at
SET DATA TYPE TIMESTAMPTZ
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE orders
ALTER COLUMN created_at
SET DATA TYPE TIMESTAMPTZ
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE payments
ALTER COLUMN created_at SET DATA TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC',
ALTER COLUMN updated_at SET DATA TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC',
ALTER COLUMN expired_at SET DATA TYPE TIMESTAMPTZ USING expired_at AT TIME ZONE 'UTC';

ALTER TABLE product_inventory
ALTER COLUMN updated_at
SET DATA TYPE TIMESTAMPTZ
USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE products 
ALTER COLUMN created_at
SET DATA TYPE TIMESTAMPTZ
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE users
ALTER COLUMN created_at
SET DATA TYPE TIMESTAMPTZ
USING created_at AT TIME ZONE 'UTC';
