@baseUrl = http://localhost:8080

### Health
GET {{baseUrl}}/health

### Create user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "NewUser2",
  "email": "newUser2@gmail.com",
  "password": "ChangeMe123!"
}

### Get user (not found)
GET {{baseUrl}}/users/<USER_ID>

### Get user (found)
GET {{baseUrl}}/users/<USER_ID>

### Register
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "NewUser4",
  "email": "newUser4@gmail.com",
  "password": "ChangeMe1234!"
}

### Login (success)
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "newUser4@gmail.com",
  "password": "ChangeMe1234!"
}

### Login (invalid credentials)
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "newUser4@gmail.com",
  "password": "wrong-password"
}

### Me (replace <TOKEN> with login token)
GET {{baseUrl}}/me
Authorization: Bearer <TOKEN>

### Create product (replace <TOKEN> with login token)
POST {{baseUrl}}/products
Authorization: Bearer <TOKEN>
Content-Type: application/json

{
  "name": "T-Shirt",
  "description": "Cotton tee",
  "price": 19.99,
  "stock": 50
}

### Create product - Tas (quantity 50)
POST {{baseUrl}}/products
Authorization: Bearer <TOKEN>
Content-Type: application/json

{
  "name": "Tas",
  "description": "Tas harian",
  "price": 79.99,
  "stock": 50
}

### PRODUCT
@productID = 2c1a33e2-450a-4934-8c29-30b279cbdb51
@tasProductID = 4bca11d2-a736-4827-a694-177b1d1ca3e8
### List products
GET {{baseUrl}}/products

### Get product by ID (replace <PRODUCT_ID> with actual product ID)
GET {{baseUrl}}/products/{{productID}}

### update product stock (replace <PRODUCT_ID> with actual product ID)
PATCH {{baseUrl}}/products/{{productID}}/stock
Content-Type: application/json

{
  "qty": 5
}

### reserve stock
POST {{baseUrl}}/products/{{productID}}/reserve
Content-Type: application/json

{
  "qty": 8
}

### reserve stock (oversell)
POST {{baseUrl}}/products/{{productID}}/reserve
Content-Type: application/json

{
  "qty": 100
}

### release reserved stock
POST {{baseUrl}}/products/{{productID}}/release
Content-Type: application/json

{
  "qty": 1
}

### confirm reserved stock
POST {{baseUrl}}/products/{{productID}}/confirm
Content-Type: application/json

{
  "qty": 1
}

### create order (T-Shirt 20, Tas 15)
POST {{baseUrl}}/orders
Authorization: Bearer <TOKEN>
Content-Type: application/json

{
  "items": [
    { "product_id": "{{productID}}", "qty": 20 },
    { "product_id": "{{tasProductID}}", "qty": 15 }
  ]
}
